### ISSUE TITLE
How to add the root_path and the trajectory_path.I got all the data,but I didn't know how to use it and I want konw how can I use the data splits.I really need your help!

### ISSUE THREAD

**Issue by dengxw8** [VCL3D/UAVA#1]

**Comment by tzole1155** [comment]
Hi dengxw8,

I think that it would be good to start with the ['visualize_dataset.py'](https://github.com/VCL3D/UAVA/blob/master/visualize_dataset.py) script which is an example for using the dataloaders and visualise several modalities included in the UAVA dataset.

There you can set the  `root_path` and the `trajectory_path` to the correct locations corresponding to your system. The script will automatically retrieve the data splits from the homonym folder.

Additionally, you can parameterize the dataloader in order to get the data you want, for example, get only the exocentric view, etc.

If you could provide more details about your issue, maybe we could help more.

Best,

Giorgos

**Comment by dengxw8** [comment]
Dear sir
I got the data named M2ED_ExoView_CDS and the trajectories,and I ran the train.py with error "expected str, bytes or os.pathlike object,not nonetype".I find no information about root path in UAVA . The describes about --root_path and --trajectory_path are so few,the data contains so many folders so that I don't know how to set the right path， it just says "Path to the root folder containing all the files"or "Specifies the root path of the data".I think my problem is about data splits because the data contains so many folders and I really want to know the right path that I can put images and trajectories into train code.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VCL3D/UAVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VCL3D/UAVA] How to add the root_path and the trajectory_path.I got all the data,but I didn't know how to use it and I want konw how can I use the data splits.I really need your help! (#1)





 
Hi dengxw8,
 
I think that it would be good to start with the 'visualize_dataset.py' script which is an example for using the dataloaders and visualise several modalities included in the UAVA dataset.
 
There you can set the  root_path and the trajectory_path to the correct locations corresponding to your system. The script will automatically retrieve the data splits from the homonym folder.
 
Additionally, you can parameterize the dataloader in order to get the data you want, for example, get only the exocentric view, etc.
 
If you could provide more details about your issue, maybe we could help more.
 
Best,
 
Giorgos

**Comment by tzole1155** [comment]
Hi dengxw8,

As I said in the above message could you try to run ['visualize_dataset.py'](https://github.com/VCL3D/UAVA/blob/master/visualize_dataset.py) in order to understand the premise of the data loading pipeline?
The config names are self-explanatory I do not think that another description is needed.
Could you also let me know the values that you set in the above arguments or even post a screenshot?
Best,
Giorgos

**Comment by dengxw8** [comment]
I added no path to&nbsp;'visualize_dataset.py'&nbsp; ,and I got the result&nbsp;



also , I set arguments and got the same result . I knew I set the wrong path so that I got the same result.I have tried so many
conbinations,and got the same result.The&nbsp;&nbsp;'train.py'&nbsp; shows this result also.

I'm new to this,and I'm so thankful you gave me so much help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VCL3D/UAVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VCL3D/UAVA] How to add the root_path and the trajectory_path.I got all the data,but I didn't know how to use it and I want konw how can I use the data splits.I really need your help! (#1)





 
Hi dengxw8,
 
As I said in the above message could you try to run 'visualize_dataset.py' in order to understand the premise of the data loading pipeline?
 The config names are self-explanatory I do not think that another description is needed.
 Could you also let me know the values that you set in the above arguments or even post a screenshot?
 Best,
 Giorgos

**Comment by tzole1155** [comment]
Hi dengxw8,

Sorry for the late reply.

Have you managed to find a solution to your issue?

In the meantime, I've updated the [README](https://github.com/VCL3D/UAVA) in order to clarify how the data structure should like and what it's needed to be set up.

Hope that this will help.

Best,

Giorgos

**Comment by dengxw8** [comment]
Thank you very much，it works ! You are so patient and I'm so greatful !

**Comment by tzole1155** [comment]
Happy that worked!

**Comment by dengxw8** [comment]
Dear sir
I ran the train.py code and I got twenty model_state files.And I've downloaded Pre-trained Models.I want to know if these models are run in inference code.The inference code is not supplied here，I want to ask is there any method to get the inference code also？

**Comment by tzole1155** [comment]
Hi dengxw8,

You are right. We have not uploaded the inference code yet.

I'll try to do this by the end of this week and let you know.

Best,

Giorgos

**Comment by dengxw8** [comment]
Thanks a lot ！

**Comment by dengxw8** [comment]
Dear sir
could you please take a moment to upload the inference code , I really need it . 
Many thanks for your great support and help!

**Comment by dengxw8** [comment]
Dear sir
   Is it possible for me to get this code , The deadline of my graduation assignment is near and now I really need it to do the next step work.My graduation will be delayed if I can not finish this part ,It would be appreciated if you could help me with this.
   sincerely.
